using System.IO;
using System.Reflection;
using System.Text.Json;
using DockerDiagram.ApplicationServices;
using DockerDiagram.Contracts;
using DockerDiagram.Models;
using DockerDiagram.ViewModels;
using DockerDiagram.Infrastructure;

namespace DockerDiagram.Tests;

public sealed class FileServiceTests
{
    [Fact]
    public void CurrentFormat_PersistsAutoGeneratedSwarmTopologyOwnership()
    {
        var file = new DiagramFile
        {
            Sheets =
            {
                new SheetData
                {
                    RuntimeKind = RuntimeKind.DockerSwarm,
                    Nodes =
                    {
                        new NodeData
                        {
                            Name = "Published 8080/tcp",
                            ResourceKind = RuntimeResourceKind.SwarmExternalTraffic,
                            IsAutoGeneratedSwarmTopologyNode = true
                        }
                    }
                }
            }
        };

        DiagramFile? restored = JsonSerializer.Deserialize<DiagramFile>(JsonSerializer.Serialize(file));

        Assert.Equal("1.42", file.Version);
        Assert.True(restored!.Sheets.Single().Nodes.Single().IsAutoGeneratedSwarmTopologyNode);
    }

    [Fact]
    public void ConnectionData_PublishModeRoundTripsAndLegacyDefaultsToIngress()
    {
        var current = new ConnectionData
        {
            RelationType = RelationType.SwarmPublishedPort,
            PublishedPort = string.Empty,
            TargetPort = "53",
            Protocol = "udp",
            PublishMode = "host"
        };

        ConnectionData? restored = JsonSerializer.Deserialize<ConnectionData>(
            JsonSerializer.Serialize(current));
        ConnectionData? legacy = JsonSerializer.Deserialize<ConnectionData>(
            """{ "RelationType": 4, "PublishedPort": "8080", "TargetPort": "80", "Protocol": "tcp" }""");

        Assert.NotNull(restored);
        Assert.Equal("host", restored.PublishMode);
        Assert.Equal(string.Empty, restored.PublishedPort);
        Assert.NotNull(legacy);
        Assert.Equal("ingress", legacy.PublishMode);
    }

    [Fact]
    public void ConnectionData_SwarmReferenceSettingsRoundTripAndLegacyOwnersDefaultToRoot()
    {
        var current = new ConnectionData
        {
            RelationType = RelationType.SwarmConfigReference,
            SwarmReferenceTarget = "/etc/app/config.yml",
            SwarmReferenceUid = "1000",
            SwarmReferenceGid = "app",
            SwarmReferenceMode = "0400"
        };

        ConnectionData? restored = JsonSerializer.Deserialize<ConnectionData>(
            JsonSerializer.Serialize(current));
        ConnectionData? legacy = JsonSerializer.Deserialize<ConnectionData>(
            """{ "RelationType": 5 }""");

        Assert.NotNull(restored);
        Assert.Equal("/etc/app/config.yml", restored.SwarmReferenceTarget);
        Assert.Equal("1000", restored.SwarmReferenceUid);
        Assert.Equal("app", restored.SwarmReferenceGid);
        Assert.Equal("0400", restored.SwarmReferenceMode);
        Assert.NotNull(legacy);
        Assert.Equal("0", legacy.SwarmReferenceUid);
        Assert.Equal("0", legacy.SwarmReferenceGid);
        Assert.Equal("0444", legacy.SwarmReferenceMode);
    }

    [Fact]
    public void WriteValidatedFileAtomically_RoundTripsAndBacksUpPreviousFile()
    {
        string directory = CreateTestDirectory();
        string path = Path.Combine(directory, "diagram.vdm");

        try
        {
            var first = new DiagramFile
            {
                Version = "test-1",
                ActiveSheetIndex = 0,
                Sheets =
                {
                    new SheetData
                    {
                        Title = "First",
                        MapWidth = 2400,
                        MapHeight = 1800,
                        Scale = 1.25,
                        Nodes =
                        {
                            new NodeData
                            {
                                Id = "node-1",
                                Name = "web",
                                Type = NodeType.Container,
                                X = 120,
                                Y = 240
                            }
                        }
                    }
                }
            };

            DiagramSaveResult firstResult = FileService.WriteValidatedFileAtomically(
                path,
                JsonSerializer.Serialize(first));

            Assert.True(firstResult.Success, firstResult.ErrorMessage);

            var second = new DiagramFile
            {
                Version = "test-2",
                Sheets = { new SheetData { Title = "Second" } }
            };

            DiagramSaveResult secondResult = FileService.WriteValidatedFileAtomically(
                path,
                JsonSerializer.Serialize(second));

            Assert.True(secondResult.Success, secondResult.ErrorMessage);
            Assert.True(File.Exists(path + ".bak"));

            var third = new DiagramFile
            {
                Version = "test-3",
                Sheets =
                {
                    new SheetData
                    {
                        Title = "Third",
                        Scale = 1.25,
                        HasViewportCenter = true,
                        ViewportCenterX = 480,
                        ViewportCenterY = 360
                    }
                }
            };

            DiagramSaveResult thirdResult = FileService.WriteValidatedFileAtomically(
                path,
                JsonSerializer.Serialize(third));

            Assert.True(thirdResult.Success, thirdResult.ErrorMessage);

            DiagramFile? restored = JsonSerializer.Deserialize<DiagramFile>(File.ReadAllText(path));
            DiagramFile? backup = JsonSerializer.Deserialize<DiagramFile>(File.ReadAllText(path + ".bak"));

            Assert.NotNull(restored);
            Assert.Equal("test-3", restored.Version);
            SheetData restoredSheet = restored.Sheets.Single();
            Assert.Equal("Third", restoredSheet.Title);
            Assert.True(restoredSheet.HasViewportCenter);
            Assert.Equal(480, restoredSheet.ViewportCenterX);
            Assert.Equal(360, restoredSheet.ViewportCenterY);
            Assert.NotNull(backup);
            Assert.Equal("test-2", backup.Version);
            Assert.Equal("Second", backup.Sheets.Single().Title);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void WriteValidatedFileAtomically_InvalidJsonPreservesExistingFile()
    {
        string directory = CreateTestDirectory();
        string path = Path.Combine(directory, "diagram.vdm");
        const string original = "original-content";

        try
        {
            File.WriteAllText(path, original);

            DiagramSaveResult result = FileService.WriteValidatedFileAtomically(path, "{ invalid json");

            Assert.False(result.Success);
            Assert.Equal(original, File.ReadAllText(path));
            Assert.False(File.Exists(path + ".bak"));
            Assert.Empty(Directory.EnumerateFiles(directory, "*.tmp"));
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void ViewportCenter_RestoresSameWorldPositionAcrossViewportSizes()
    {
        IDockerService dockerService = DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>();
        IDialogService dialogService = DispatchProxy.Create<IDialogService, UnexpectedDialogServiceProxy>();
        var sheet = new SheetViewModel(
            "Viewport",
            new ConnectionProfile(),
            dockerService,
            dialogService)
        {
            Scale = 1.25,
            OffsetX = -100,
            OffsetY = -50
        };

        Assert.False(sheet.RestoreViewportOffset(viewportWidth: 1000, viewportHeight: 800));
        Assert.True(sheet.CaptureViewportCenter(viewportWidth: 1000, viewportHeight: 800));
        Assert.Equal(480, sheet.ViewportCenterX);
        Assert.Equal(360, sheet.ViewportCenterY);

        sheet.OffsetX = 0;
        sheet.OffsetY = 0;

        Assert.True(sheet.RestoreViewportOffset(viewportWidth: 1400, viewportHeight: 1000));
        Assert.Equal(100, sheet.OffsetX);
        Assert.Equal(50, sheet.OffsetY);
    }

    [Fact]
    public async Task LoadDiagramFromPathAsync_ReconstructionFailurePreservesCurrentWorkspace()
    {
        string directory = CreateTestDirectory();
        string path = Path.Combine(directory, "broken-after-parse.vdm");
        File.WriteAllText(path, """
            {
              "Version": "1.39",
              "Sheets": [
                {
                  "Title": "Broken",
                  "RuntimeKind": 0,
                  "Nodes": [],
                  "Groups": null,
                  "Connections": []
                }
              ]
            }
            """);

        IDockerService dockerService = DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>();
        IDialogService dialogService = DispatchProxy.Create<IDialogService, LenientDialogServiceProxy>();
        using var factory = new DockerServiceFactory(_ =>
            DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>());
        using var main = new MainViewModel(dockerService, dialogService, factory);
        SheetViewModel originalSheet = main.ActiveSheet!;

        try
        {
            bool loaded = await FileService.LoadDiagramFromPathAsync(
                main,
                path,
                dockerService,
                dockerService,
                dockerService,
                dialogService);

            Assert.False(loaded);
            Assert.Same(originalSheet, main.ActiveSheet);
            Assert.Contains(originalSheet, main.AllSheets);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(99)]
    public async Task LoadDiagramFromPathAsync_InvalidActiveSheetIndexFallsBackToFirstSheet(int activeSheetIndex)
    {
        string directory = CreateTestDirectory();
        string path = Path.Combine(directory, "invalid-active-index.vdm");
        var file = new DiagramFile
        {
            ActiveSheetIndex = activeSheetIndex,
            Sheets =
            {
                new SheetData { Title = "First" },
                new SheetData { Title = "Second" }
            }
        };
        File.WriteAllText(path, JsonSerializer.Serialize(file));

        IDockerService dockerService = DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>();
        IDialogService dialogService = DispatchProxy.Create<IDialogService, LenientDialogServiceProxy>();
        using var factory = new DockerServiceFactory(_ =>
            DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>());
        using var main = new MainViewModel(dockerService, dialogService, factory);

        try
        {
            bool loaded = await FileService.LoadDiagramFromPathAsync(
                main,
                path,
                dockerService,
                dockerService,
                dockerService,
                dialogService);

            Assert.True(loaded);
            Assert.NotNull(main.ActiveSheet);
            Assert.Equal("First", main.ActiveSheet.Title);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    private static string CreateTestDirectory()
    {
        string directory = Path.Combine(Path.GetTempPath(), "DockerDiagram.Tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        return directory;
    }
}

public class UnexpectedDialogServiceProxy : DispatchProxy
{
    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args) =>
        throw new NotSupportedException($"Unexpected dialog service call: {targetMethod?.Name}");
}

public class LenientDialogServiceProxy : DispatchProxy
{
    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
    {
        Type returnType = targetMethod?.ReturnType ?? typeof(void);
        if (returnType == typeof(void)) return null;
        if (returnType == typeof(bool)) return true;
        if (returnType == typeof(DialogChoice)) return DialogChoice.Cancel;
        if (returnType == typeof(Task)) return Task.CompletedTask;
        if (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(Task<>))
        {
            Type valueType = returnType.GetGenericArguments()[0];
            object? value = valueType.IsValueType ? Activator.CreateInstance(valueType) : null;
            return typeof(Task).GetMethod(nameof(Task.FromResult))!
                .MakeGenericMethod(valueType)
                .Invoke(null, new[] { value });
        }
        return returnType.IsValueType ? Activator.CreateInstance(returnType) : null;
    }
}
