using DockerDiagram.ApplicationServices;
using DockerDiagram.Contracts;
using DockerDiagram.Diagram;
using DockerDiagram.Models;

namespace DockerDiagram.ViewModels
{
    public partial class MainViewModel
    {
        private async Task RestoreExistingSwarmServiceTopologyAsync(
            SheetViewModel sheet,
            NodeViewModel serviceNode)
        {
            if (sheet.DockerService is not ISwarmService swarmService ||
                string.IsNullOrWhiteSpace(serviceNode.ContainerId))
            {
                return;
            }

            object raw = await swarmService.InspectSwarmServiceRawAsync(serviceNode.ContainerId);
            SwarmServiceEditSnapshot snapshot = SwarmServiceSpecReader.Read(raw);
            SwarmServiceTopologyProjection topology = SwarmServiceTopologyProjectionReader.Read(snapshot);
            var warnings = new List<string>();
            using IDisposable updateScope = Explorer.DeferAvailableItemsUpdates();

            RestorePublishedPorts(sheet, serviceNode, topology.PublishedPorts);
            RestoreVolumeMounts(sheet, serviceNode, topology.Mounts, warnings);
            await RestoreOverlayNetworksAsync(sheet, serviceNode, topology.Networks, warnings);
            RestoreDataReferences(sheet, serviceNode, topology.DataReferences);

            serviceNode.SwarmDiagramManagesPublishedPorts = topology.PublishedPorts.Count > 0;
            serviceNode.SwarmDiagramManagesMounts = topology.Mounts.Any(mount => mount.Kind == SwarmMountKind.Volume);
            serviceNode.SwarmDiagramManagesNetworks = topology.Networks.Count > 0;
            serviceNode.IsSwarmDiagramDirty = false;

            if (warnings.Count > 0)
            {
                _dialogService.ShowInfo(
                    "Service는 배치했지만 다음 항목은 현재 다이어그램 형식으로 복원하지 않았습니다:\n" +
                    string.Join("\n", warnings.Distinct(StringComparer.OrdinalIgnoreCase)),
                    "Swarm Topology Import");
            }
        }

        private void RestorePublishedPorts(
            SheetViewModel sheet,
            NodeViewModel serviceNode,
            IReadOnlyList<SwarmPublishedPortOptions> ports)
        {
            for (int index = 0; index < ports.Count; index++)
            {
                SwarmPublishedPortOptions port = ports[index];
                var traffic = new NodeViewModel(sheet.DockerService, sheet.DockerService, _dialogService)
                {
                    Name = port.PublishedPort.HasValue
                        ? $"Published {port.PublishedPort.Value}/{port.Protocol.ToString().ToLowerInvariant()}"
                        : $"Dynamic → {port.TargetPort}/{port.Protocol.ToString().ToLowerInvariant()}",
                    ImageName = "external",
                    Type = NodeType.Internet,
                    ParentSheet = sheet,
                    X = serviceNode.X - 240,
                    Y = serviceNode.Y + (index * 100),
                    RuntimeKind = RuntimeKind.DockerSwarm,
                    ResourceKind = RuntimeResourceKind.SwarmExternalTraffic,
                    BindingState = RuntimeBindingState.Bound,
                    IsAutoGeneratedSwarmTopologyNode = true,
                    DetailStatus = $"Published by service {serviceNode.Name}",
                    StatusColor = "#28A745",
                    IsDockerConnected = true
                };
                sheet.Nodes.Add(traffic);

                var connector = new ConnectorViewModel(
                    traffic,
                    serviceNode,
                    PortDirection.Right,
                    PortDirection.Left,
                    _dialogService)
                {
                    RelationType = RelationType.SwarmPublishedPort,
                    PublishedPort = port.PublishedPort?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,
                    TargetPort = port.TargetPort.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    Protocol = port.Protocol.ToString().ToLowerInvariant(),
                    PublishMode = port.PublishMode.ToString().ToLowerInvariant(),
                    IsBidirectional = false
                };
                sheet.Connectors.Add(connector);
            }
        }

        private void RestoreVolumeMounts(
            SheetViewModel sheet,
            NodeViewModel serviceNode,
            IReadOnlyList<SwarmMountOptions> mounts,
            ICollection<string> warnings)
        {
            int index = 0;
            foreach (SwarmMountOptions mount in mounts)
            {
                if (mount.Kind != SwarmMountKind.Volume)
                {
                    warnings.Add($"- {mount.Kind} mount: {mount.Source} → {mount.Target}");
                    continue;
                }
                if (string.IsNullOrWhiteSpace(mount.Source))
                {
                    warnings.Add($"- anonymous volume mount → {mount.Target}");
                    continue;
                }

                NodeViewModel? volume = sheet.Nodes.FirstOrDefault(node =>
                    node.ResourceKind == RuntimeResourceKind.SwarmVolume &&
                    string.Equals(node.EffectiveVolumeName, mount.Source, StringComparison.OrdinalIgnoreCase));
                if (volume == null)
                {
                    volume = new NodeViewModel(sheet.DockerService, sheet.DockerService, _dialogService)
                    {
                        Name = mount.Source,
                        DockerVolumeName = mount.Source,
                        Driver = string.IsNullOrWhiteSpace(mount.VolumeDriver) ? "local" : mount.VolumeDriver,
                        ImageName = string.IsNullOrWhiteSpace(mount.VolumeDriver) ? "local" : mount.VolumeDriver,
                        Type = NodeType.Volume,
                        ParentSheet = sheet,
                        X = serviceNode.X + 260,
                        Y = serviceNode.Y + (index * 110),
                        RuntimeKind = RuntimeKind.DockerSwarm,
                        ResourceKind = RuntimeResourceKind.SwarmVolume,
                        BindingState = RuntimeBindingState.Bound,
                        VolumeLabels = new Dictionary<string, string>(mount.VolumeLabels ?? new Dictionary<string, string>()),
                        VolumeDriverOptions = new Dictionary<string, string>(mount.VolumeDriverOptions ?? new Dictionary<string, string>()),
                        DetailStatus = $"Declared by service {serviceNode.Name} · task-node scoped",
                        StatusColor = "#5B6B7A",
                        IsDockerConnected = false
                    };
                    sheet.Nodes.Add(volume);
                }

                if (!HasRelation(sheet, serviceNode, volume, RelationType.VolumeMount))
                {
                    sheet.Connectors.Add(new ConnectorViewModel(
                        serviceNode,
                        volume,
                        PortDirection.Right,
                        PortDirection.Left,
                        _dialogService)
                    {
                        RelationType = RelationType.VolumeMount,
                        MountPath = mount.Target,
                        IsBidirectional = false
                    });
                }
                index++;
            }
        }

        private async Task RestoreOverlayNetworksAsync(
            SheetViewModel sheet,
            NodeViewModel serviceNode,
            IReadOnlyList<SwarmNetworkAttachmentOptions> attachments,
            ICollection<string> warnings)
        {
            if (attachments.Count == 0) return;
            IReadOnlyList<DockerNetworkGroup> cachedNetworks = Explorer.GetSwarmNetworksSnapshot();
            List<DockerNetworkGroup> networks = cachedNetworks.Count > 0
                ? cachedNetworks.ToList()
                : await ((INetworkService)sheet.DockerService).GetNetworksAsync();
            for (int index = 0; index < attachments.Count; index++)
            {
                SwarmNetworkAttachmentOptions attachment = attachments[index];
                DockerNetworkGroup? network = networks.FirstOrDefault(candidate =>
                        string.Equals(candidate.Id, attachment.Target, StringComparison.OrdinalIgnoreCase))
                    ?? networks.FirstOrDefault(candidate =>
                        string.Equals(candidate.Name, attachment.Target, StringComparison.OrdinalIgnoreCase));
                if (network == null || !SwarmResourceFilter.IsOverlayNetwork(network))
                {
                    warnings.Add($"- overlay network target: {attachment.Target}");
                    continue;
                }

                GroupViewModel? group = sheet.Groups.FirstOrDefault(candidate =>
                    candidate.ResourceKind == RuntimeResourceKind.SwarmOverlayNetwork &&
                    (string.Equals(candidate.Id, network.Id, StringComparison.OrdinalIgnoreCase) ||
                     string.Equals(candidate.DockerNetworkName, network.Name, StringComparison.OrdinalIgnoreCase)));
                if (group == null)
                {
                    double inset = index * 20;
                    group = new GroupViewModel(
                        serviceNode.X - 60 - inset,
                        serviceNode.Y - 60 - inset,
                        GroupViewModel.MinimumWidth + (inset * 2),
                        GroupViewModel.MinimumHeight + (inset * 2),
                        sheet.DockerService,
                        _dialogService,
                        network.Name,
                        GroupType.Network)
                    {
                        Id = network.Id,
                        Driver = "overlay",
                        ComposeNetworkName = network.Name,
                        RuntimeKind = RuntimeKind.DockerSwarm,
                        ResourceKind = RuntimeResourceKind.SwarmOverlayNetwork,
                        BindingState = RuntimeBindingState.Bound,
                        IsDockerConnected = true,
                        ParentSheet = sheet
                    };
                    sheet.AddGroup(group);
                }
                await group.AddNodeAsync(serviceNode, isRestoring: true);
            }
            sheet.UpdateGroupLayering();
        }

        private void RestoreDataReferences(
            SheetViewModel sheet,
            NodeViewModel serviceNode,
            IReadOnlyList<SwarmServiceDataReference> references)
        {
            for (int index = 0; index < references.Count; index++)
            {
                SwarmServiceDataReference reference = references[index];
                RuntimeResourceKind kind = reference.Kind == SwarmDataResourceKind.Secret
                    ? RuntimeResourceKind.SwarmSecret
                    : RuntimeResourceKind.SwarmConfig;
                NodeViewModel? resource = sheet.Nodes.FirstOrDefault(node =>
                    node.ResourceKind == kind &&
                    string.Equals(node.ContainerId, reference.ResourceId, StringComparison.OrdinalIgnoreCase));
                if (resource == null)
                {
                    resource = new NodeViewModel(sheet.DockerService, sheet.DockerService, _dialogService)
                    {
                        Name = reference.ResourceName,
                        ImageName = reference.Kind == SwarmDataResourceKind.Secret ? "swarm-secret" : "swarm-config",
                        Type = NodeType.Container,
                        ParentSheet = sheet,
                        X = serviceNode.X + 260,
                        Y = serviceNode.Y + 220 + (index * 100),
                        ContainerId = reference.ResourceId,
                        RuntimeKind = RuntimeKind.DockerSwarm,
                        ResourceKind = kind,
                        BindingState = RuntimeBindingState.Bound,
                        DetailStatus = $"Bound · {ShortId(reference.ResourceId)}",
                        StatusColor = reference.Kind == SwarmDataResourceKind.Secret ? "#C08A00" : "#4D7C6F",
                        IsDockerConnected = true
                    };
                    sheet.Nodes.Add(resource);
                }

                RelationType relation = reference.Kind == SwarmDataResourceKind.Secret
                    ? RelationType.SwarmSecretReference
                    : RelationType.SwarmConfigReference;
                if (HasRelation(sheet, serviceNode, resource, relation)) continue;
                sheet.Connectors.Add(new ConnectorViewModel(
                    serviceNode,
                    resource,
                    PortDirection.Right,
                    PortDirection.Left,
                    _dialogService)
                {
                    RelationType = relation,
                    SwarmReferenceTarget = reference.FileName,
                    SwarmReferenceUid = reference.Uid,
                    SwarmReferenceGid = reference.Gid,
                    SwarmReferenceMode = Convert.ToString(reference.Mode, 8).PadLeft(4, '0'),
                    IsBidirectional = false
                });
            }
        }

        private static bool HasRelation(
            SheetViewModel sheet,
            IConnectableItem first,
            IConnectableItem second,
            RelationType relation) =>
            sheet.Connectors.Any(connector =>
                connector.RelationType == relation &&
                ((ReferenceEquals(connector.Source, first) && ReferenceEquals(connector.Target, second)) ||
                 (ReferenceEquals(connector.Source, second) && ReferenceEquals(connector.Target, first))));
    }
}
