using DockerDiagram.ApplicationServices;
using DockerDiagram.Contracts;
using DockerDiagram.Diagram;
using DockerDiagram.Models;
using DockerDiagram.ViewModels;
using System.Reflection;

namespace DockerDiagram.Tests;

public sealed class DiagramDeletionSupportTests
{
    [Theory]
    [InlineData(RuntimeKind.DockerEngine, RelationType.VolumeMount, true)]
    [InlineData(RuntimeKind.DockerSwarm, RelationType.VolumeMount, false)]
    [InlineData(RuntimeKind.DockerSwarm, RelationType.SwarmPublishedPort, false)]
    public void StandaloneVolumeUnmount_IsNeverUsedForSwarmRelations(
        RuntimeKind runtimeKind,
        RelationType relationType,
        bool expected)
    {
        Assert.Equal(
            expected,
            DiagramDeletionSupport.RequiresStandaloneVolumeUnmount(runtimeKind, relationType));
    }

    [Fact]
    public async Task RemoveOverlayGroup_PreservesServiceCoordinatesAndMarksTopologyDirty()
    {
        (SheetViewModel sheet, IDockerService dockerService, IDialogService dialogService) = CreateSwarmSheet();
        NodeViewModel service = CreateService(sheet, dockerService, dialogService, 140, 260);
        var overlay = new GroupViewModel(
            80,
            160,
            420,
            320,
            dockerService,
            dialogService,
            "frontend",
            GroupType.Network)
        {
            ParentSheet = sheet,
            RuntimeKind = RuntimeKind.DockerSwarm,
            ResourceKind = RuntimeResourceKind.SwarmOverlayNetwork,
            BindingState = RuntimeBindingState.Bound
        };
        sheet.AddGroup(overlay);
        await overlay.AddNodeAsync(service, isRestoring: true);
        service.IsSwarmDiagramDirty = false;

        DiagramDeletionSupport.RemoveGroupFromDiagram(
            sheet,
            overlay,
            Array.Empty<ConnectorViewModel>());

        Assert.Equal(140, service.X);
        Assert.Equal(260, service.Y);
        Assert.Contains(service, sheet.Nodes);
        Assert.DoesNotContain(overlay, sheet.Groups);
        Assert.Empty(overlay.ContainedNodes);
        Assert.True(service.IsSwarmDiagramDirty);
    }

    [Fact]
    public async Task RemoveService_RemovesOnlyItsAutoGeneratedPublishedPortNode()
    {
        (SheetViewModel sheet, IDockerService dockerService, IDialogService dialogService) = CreateSwarmSheet();
        NodeViewModel service = CreateService(sheet, dockerService, dialogService, 300, 200);
        NodeViewModel importedTraffic = CreateTraffic(
            sheet,
            dockerService,
            dialogService,
            "Imported port",
            isAutoGenerated: true);
        NodeViewModel userTraffic = CreateTraffic(
            sheet,
            dockerService,
            dialogService,
            "User traffic",
            isAutoGenerated: false);
        sheet.Connectors.Add(CreatePublishedPort(importedTraffic, service, dialogService));
        sheet.Connectors.Add(CreatePublishedPort(userTraffic, service, dialogService));

        IReadOnlyList<NodeViewModel> dependents =
            DiagramDeletionSupport.FindExclusiveAutoGeneratedDependents(sheet, service);
        Assert.Equal(new[] { importedTraffic }, dependents);

        await sheet.RemoveNodeAsync(service);

        Assert.DoesNotContain(service, sheet.Nodes);
        Assert.DoesNotContain(importedTraffic, sheet.Nodes);
        Assert.Contains(userTraffic, sheet.Nodes);
        Assert.Empty(sheet.Connectors);
    }

    private static (SheetViewModel Sheet, IDockerService DockerService, IDialogService DialogService)
        CreateSwarmSheet()
    {
        IDockerService dockerService = DispatchProxy.Create<IDockerService, TrackingDockerServiceProxy>();
        IDialogService dialogService = DispatchProxy.Create<IDialogService, UnexpectedDialogServiceProxy>();
        var sheet = new SheetViewModel(
            "Swarm",
            new ConnectionProfile { RuntimeKind = RuntimeKind.DockerSwarm },
            dockerService,
            dialogService,
            RuntimeKind.DockerSwarm);
        return (sheet, dockerService, dialogService);
    }

    private static NodeViewModel CreateService(
        SheetViewModel sheet,
        IDockerService dockerService,
        IDialogService dialogService,
        double x,
        double y)
    {
        var service = new NodeViewModel(dockerService, dockerService, dialogService)
        {
            Name = "api",
            Type = NodeType.Container,
            ParentSheet = sheet,
            X = x,
            Y = y,
            RuntimeKind = RuntimeKind.DockerSwarm,
            ResourceKind = RuntimeResourceKind.SwarmService,
            BindingState = RuntimeBindingState.Bound
        };
        sheet.Nodes.Add(service);
        return service;
    }

    private static NodeViewModel CreateTraffic(
        SheetViewModel sheet,
        IDockerService dockerService,
        IDialogService dialogService,
        string name,
        bool isAutoGenerated)
    {
        var traffic = new NodeViewModel(dockerService, dockerService, dialogService)
        {
            Name = name,
            Type = NodeType.Internet,
            ParentSheet = sheet,
            RuntimeKind = RuntimeKind.DockerSwarm,
            ResourceKind = RuntimeResourceKind.SwarmExternalTraffic,
            BindingState = RuntimeBindingState.Bound,
            IsAutoGeneratedSwarmTopologyNode = isAutoGenerated
        };
        sheet.Nodes.Add(traffic);
        return traffic;
    }

    private static ConnectorViewModel CreatePublishedPort(
        NodeViewModel traffic,
        NodeViewModel service,
        IDialogService dialogService) =>
        new(traffic, service, PortDirection.Right, PortDirection.Left, dialogService)
        {
            RelationType = RelationType.SwarmPublishedPort,
            PublishedPort = "8080",
            TargetPort = "80",
            IsBidirectional = false
        };
}
