using DockerDiagram.Contracts;
using DockerDiagram.Models;
using DockerDiagram.ViewModels;

namespace DockerDiagram.ApplicationServices
{
    /// <summary>
    /// 다이어그램 삭제 시 런타임별 의미와 함께 제거해야 하는 시각 요소를 한곳에서 판단합니다.
    /// </summary>
    internal static class DiagramDeletionSupport
    {
        public static bool RequiresStandaloneVolumeUnmount(
            RuntimeKind runtimeKind,
            RelationType relationType) =>
            runtimeKind != RuntimeKind.DockerSwarm && relationType == RelationType.VolumeMount;

        public static IReadOnlyList<NodeViewModel> FindExclusiveAutoGeneratedDependents(
            SheetViewModel sheet,
            NodeViewModel owner)
        {
            if (owner.ResourceKind != RuntimeResourceKind.SwarmService)
                return Array.Empty<NodeViewModel>();

            return sheet.Connectors
                .Where(connector =>
                    connector.RelationType == RelationType.SwarmPublishedPort &&
                    (ReferenceEquals(connector.Source, owner) || ReferenceEquals(connector.Target, owner)))
                .Select(connector => ReferenceEquals(connector.Source, owner)
                    ? connector.Target
                    : connector.Source)
                .OfType<NodeViewModel>()
                .Where(node =>
                    node.IsAutoGeneratedSwarmTopologyNode &&
                    sheet.Connectors.Count(connector =>
                        ReferenceEquals(connector.Source, node) || ReferenceEquals(connector.Target, node)) == 1)
                .Distinct()
                .ToArray();
        }

        public static void RemoveGroupFromDiagram(
            SheetViewModel sheet,
            GroupViewModel group,
            IEnumerable<ConnectorViewModel> connectors)
        {
            NodeViewModel[] affectedServices = group.ResourceKind == RuntimeResourceKind.SwarmOverlayNetwork
                ? group.ContainedNodes
                    .Where(node => node.ResourceKind == RuntimeResourceKind.SwarmService)
                    .ToArray()
                : Array.Empty<NodeViewModel>();

            foreach (ConnectorViewModel connector in connectors.ToArray())
                sheet.Connectors.Remove(connector);

            group.ContainedNodes.Clear();
            sheet.Groups.Remove(group);
            sheet.UpdateGroupLayering();

            foreach (NodeViewModel service in affectedServices)
                service.IsSwarmDiagramDirty = true;
        }
    }
}
